**CLASE DE INTRODUCCIÓN AL MACHINE LEARNING AUTO 1 - EDA pandas**

**POR:** Yomin Jaramillo Múnera


**BASADO EN:**

https://towardsdatascience.com/an-introduction-to-pandas-29d15a7da6d

https://pandas.pydata.org/docs/user_guide/index.html

Pandas es un paquete especializado que permite hacer el analisis de datos y nos facilita el trabajo con bases de datos externas. Es una herramienta popular para abordar el  análisis exploratorio de datos - EDA (EXploratory Data Analysis)

In [1]:
import pandas as pd # como numpy generalmente se abrevia como np, por lo general pandas se abrevia como pd
import numpy as np

La principal aplicación de pandas es el trabajo con Dataframes, los cuales son definidos como: Datos tabulares bidimensionales, de tamaño variable y potencialmente heterogéneos.La estructura de datos también contiene ejes etiquetados (filas y columnas).
El dataframe es la principal estructura de datos de pandas.

Por lo tanto hablamos de una estructura de datos bidimensional (comparable con una matriz), con la diferencia que los tipos de datos en la estructura puede ser diferente. Al igual que la matriz, se organiza en filas y columnas.

**CREACION DE UNA SERIE**

In [2]:
# Desde una lista de Python (índice por defecto)
s1 = pd.Series([10, 20, 30, 40, 50])
# Desde una lista con un índice personalizado
s2 = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
# Desde un diccionario (las claves se convierten en índices)
diccionario = {'Manzana': 3, 'Banana': 5, 'Naranja': 2}
s3 = pd.Series(diccionario)
# Desde un array de NumPy
np_array = np.array([5, 10, 15, 20])
s4 = pd.Series(np_array)
s3

Manzana    3
Banana     5
Naranja    2
dtype: int64

In [3]:
# Acceso por índice numérico (posición)
print("Elemento en la posición 0:", s1[0]) # Output: 3
# Acceso por etiqueta de índice
print("Valor de 'Banana':", s3['Banana']) # Output: 5
# Slicing por posición (exclusivo el final)
print("Elementos de la posición 0 a 1 (excluido 2):")
print(s3[0:2])
# Slicing por etiqueta (inclusivo el final)
print("Elementos desde 'Manzana' hasta 'Naranja'(incluido Naranja):")
print(s3['Manzana':'Naranja'])
# Indexación Booleana (filtrado)
print("Frutas con valor > 2:")
print(s3[s3 > 2])

Elemento en la posición 0: 10
Valor de 'Banana': 5
Elementos de la posición 0 a 1 (excluido 2):
Manzana    3
Banana     5
dtype: int64
Elementos desde 'Manzana' hasta 'Naranja'(incluido Naranja):
Manzana    3
Banana     5
Naranja    2
dtype: int64
Frutas con valor > 2:
Manzana    3
Banana     5
dtype: int64

**CREACIÓN DE UN DATAFRAME**

En general, existen multiples formas de crear un Dataframe, desde una lista, desde un diccionario, desde un array de numpy o incluso se pueden importar archivos externos como .csv, .xls, o sql

In [4]:
#Desde una lista
Animes_favoritos = [['Shingeki no Kyogin', 'Eren', "Shonen"], ['Naruto', 'Naruto'], ['Death note', 'Yagami',"Shonen"],["One Piece"], ["Saint Seiya", "Seiya", "Shonen", "4", "Athenea"]]
df_animes = pd.DataFrame(Animes_favoritos)
df_animes

                    0       1       2    3        4
0  Shingeki no Kyogin    Eren  Shonen  NaN      NaN
1              Naruto  Naruto     NaN  NaN      NaN
2          Death note  Yagami  Shonen  NaN      NaN
3           One Piece     NaN     NaN  NaN      NaN
4         Saint Seiya   Seiya  Shonen    4  Athenea

In [5]:
#Desde un diccionario
dict1 = {'Exercises': ['Running','Walking','Cycling'],
         'Mileage': [250, 1000, 550]}
df = pd.DataFrame(dict1)
df

  Exercises  Mileage
0   Running      250
1   Walking     1000
2   Cycling      550

In [6]:
#Desde un diccionario con listas de igual longitud
dict = {"country":["Brazil", "Russia", "India", "China", "South Africa"],
"capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
"area":[8.516, 17.10, 3.286, 9.597, 1.221],
"population":[200.4, 143.5, 1252, 1357, 52.98]}
#Llaves→ etiquetas de las columnas
#Valores → los datos de cada columna

brics = pd.DataFrame(dict)
brics

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

**EJERCICIO 1:** Construir un Dataframe a partir de un array de numpy

In [7]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df= pd.DataFrame(matriz, columns=['A', 'B', 'C'], index=['Fila1', 'Fila2', 'Fila3'])
df

       A  B  C
Fila1  1  2  3
Fila2  4  5  6
Fila3  7  8  9

**IMPORTAR BASES DE DATOS**

A pesar de que hay varias metodologías para la creación de Dataframes, como las vistas anteriormente, es muy común que se haga la importación de base de datos externas.
En general, teniendo en cuenta la gran acogida de pandas como framework de análisis de datos, varios formatos pueden ser convertidos usando el pd.
Recomiendo seguir la documentación oficial disponible según la necesidad que tenga:

https://pandas.pydata.org/docs/user_guide/index.html

Normalmente el archivo de la base de datos externa es ubicado en la misma carpeta del script de python o el notebook desde el que se va a llamar. En este notebook se trabajo con un archivo con extensión ".csv" el cual se ubico en la misma carpeta que este notebook.

Para la sincronización del notebook con google drive se ejecuta lo siguiente:

In [8]:
from google.colab import drive
import sys
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

El codigo les solicitará una autenticación para sincronizar los datos de su drive al noteebok presente. Una vez alli el folder de la barra del menú a la izquierda le debe aparecer una carpeta llamada Drive, lo cual indíca la sincronización de la información.
Despliegue la carpeta de Drive y busque la ubicación donde se alojan el notebook y la base de datos,  posteriormente, copie el path y corra el siguiente codigo para ubicarse directamente en dicha carpeta

In [ ]:
#sys.path.append('/content/drive/MyDrive/Colab Notebooks/Auto 1')
%cd '/content/drive/MyDrive/Colab Notebooks/Auto 1'
#puede confirmar su ubiación mediante:
%ls

/content/drive/MyDrive/Colab Notebooks/Auto 1
 bmi.csv                               Matplotlib_introduction.ipynb
'Clasificacion cardiacas.ipynb'       'Metricas de clasificacion.ipynb'
 Class3and4_Operations.ipynb          'Normalization Introduction.ipynb'
 cricketer.csv                         Pandas_Introduction.ipynb
 Data.csv                             'Parcial 1'/
 EMG-data.csv                          Perceptron_full.ipynb
 Final/                                Perceptron.ipynb
 heart.csv                             RegresionLineal-MultiVariables.ipynb
 IntroductionPerceptron_simple.ipynb   RegresionLinealSimple.ipynb
'Laboratorio 1'/                       Untitled0.ipynb
'Laboratorio 2'/                       Untitled1.ipynb
'Laboratorio final'/                   Variables.ipynb
 LinearClassifiers.ipynb               Vectores_Matrices_Tensores.ipynb

Una vez en la ubicación, podemos hacer la lectura de la base de datos. En este caso se va a trabajar con cricker.csv por lo que se usa el método read_csv, pero recuerde que puede varia según el archivo que desee importar

In [21]:
df = pd.read_csv('../data/cricketer.csv')
df

      Unnamed: 0   left  year  life  dead  acd  kia  inbed  cause
0              1  right  1890   102     0    0    0      0  alive
1              2   left  1892   100     0    0    0      0  alive
2              3  right  1893    99     0    0    0      0  alive
3              4  right  1894    98     0    0    0      0  alive
4              5  right  1896    96     0    0    0      0  alive
...          ...    ...   ...   ...   ...  ...  ...    ...    ...
5955        6168  right  1890    46     1    0    0      1  inbed
5956        6169  right  1919    63     1    0    0      1  inbed
5957        6170   left  1876    88     1    0    0      1  inbed
5958        6171   left  1850    65     1    0    0      1  inbed
5959        6172   left  1885    32     1    1    1      0    acd

[5960 rows x 9 columns]

**PRIMEROS PASOS**

Es ideal hacer una visualización general de los datos para familiarizarse con ellos y estudiar la composición de la base de datos. Para esto se recomienda el uso de algunos de los siguientes métodos:

In [ ]:
df.head(10) #toma las 5 primeras muestras de la base de datos

   Unnamed: 0   left  year  life  dead  acd  kia  inbed  cause
0           1  right  1890   102     0    0    0      0  alive
1           2   left  1892   100     0    0    0      0  alive
2           3  right  1893    99     0    0    0      0  alive
3           4  right  1894    98     0    0    0      0  alive
4           5  right  1896    96     0    0    0      0  alive
5           6  right  1896    96     0    0    0      0  alive
6           7  right  1897    95     0    0    0      0  alive
7           8  right  1898    94     0    0    0      0  alive
8           9   left  1898    94     0    0    0      0  alive
9          10   left  1898    94     0    0    0      0  alive

In [ ]:
df.tail() #toma las ultimas 5 muestras de la base de datos

      Unnamed: 0   left  year  life  dead  acd  kia  inbed  cause
5955        6168  right  1890    46     1    0    0      1  inbed
5956        6169  right  1919    63     1    0    0      1  inbed
5957        6170   left  1876    88     1    0    0      1  inbed
5958        6171   left  1850    65     1    0    0      1  inbed
5959        6172   left  1885    32     1    1    1      0    acd

In [ ]:
df.info()#Muestra información general de la base de datos y tipos de datos de las columnas

<class 'pandas.DataFrame'>
RangeIndex: 5960 entries, 0 to 5959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5960 non-null   int64
 1   left        5960 non-null   str
 2   year        5960 non-null   int64
 3   life        5960 non-null   int64
 4   dead        5960 non-null   int64
 5   acd         5960 non-null   int64
 6   kia         5960 non-null   int64
 7   inbed       5960 non-null   int64
 8   cause       5960 non-null   str
dtypes: int64(7), str(2)
memory usage: 419.2 KB

In [ ]:
df.describe()#muestra descripción estadistica de los datos

,Unnamed: 0,year,life,dead,acd,kia,inbed
count,5960.000000,5960.000000,5960.000000,5960.000000,5960.000000,5960.000000,5960.000000
mean,3035.931879,1905.639430,61.836913,0.568289,0.031544,0.020134,0.536745
std,1783.262498,33.042651,16.602504,0.495356,0.174796,0.140471,0.498690
min,1.000000,1840.000000,19.000000,0.000000,0.000000,0.000000,0.000000
25%,1490.750000,1878.000000,49.000000,0.000000,0.000000,0.000000,0.000000
50%,2992.000000,1908.000000,63.000000,1.000000,0.000000,0.000000,1.000000
75%,4579.250000,1935.000000,76.000000,1.000000,0.000000,0.000000,1.000000
max,6172.000000,1960.000000,102.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.sample(100).sort_values('life') #imprime una cantidad especifica de muestras de forma aleatoria

      Unnamed: 0   left  year  life  dead  acd  kia  inbed  cause
5888        6100   left  1890    24     1    1    1      0    acd
4989        5138  right  1864    26     1    0    0      1  inbed
2532        2533  right  1960    32     0    0    0      0  alive
2534        2535  right  1960    32     0    0    0      0  alive
3522        3569   left  1867    33     1    0    0      1  inbed
...          ...    ...   ...   ...   ...  ...  ...    ...    ...
43            44  right  1906    86     0    0    0      0  alive
3616        3668   left  1896    89     1    0    0      1  inbed
2817        2826  right  1875    90     1    0    0      1  inbed
3001        3015  right  1886    92     1    0    0      1  inbed
2682        2687  right  1873    94     1    0    0      1  inbed

[100 rows x 9 columns]

In [ ]:
df["cause"].unique()#define los posibles valores que puede tomar la columna 'cause'

<StringArray>
['alive', 'inbed', 'acd']
Length: 3, dtype: str

In [ ]:
for i in df["cause"].unique():
  print(i)

alive
inbed
acd

In [ ]:
for i in df["cause"]:
  print(i)

alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
alive
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
acd
inbed
inbed
acd
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
inbed
acd
inbed
inbed
inbed

**SELECCIÓN DE FILAS Y COLUMNAS**

Para la referenciación de filas y/o columnas en un DataFrame se hace uso de .loc[  ] y .iloc[  ], el uso de uno  o de otro depende de la referenciación que usted desee hacer par acceder a la información.

.loc[  ] se usa si usted conoce la etiqueta o nombre de la fila o columna.

In [ ]:
b1=df.loc[0:10,"year"]
basededatos=df.loc[0:100,["year", "left", "cause"]]
basededatos

     year   left  cause
0    1890  right  alive
1    1892   left  alive
2    1893  right  alive
3    1894  right  alive
4    1896  right  alive
..    ...    ...    ...
96   1909  right  alive
97   1909  right  alive
98   1909  right  alive
99   1909  right  alive
100  1909   left  alive

[101 rows x 3 columns]

In [ ]:
print(df.loc[10,:])

Unnamed: 0       11
left          right
year           1900
life             92
dead              0
acd               0
kia               0
inbed             0
cause         alive
Name: 10, dtype: object

.iloc[  ] se usa para refenciase solo con los indices

In [ ]:
df.iloc[15:18,:4]

    Unnamed: 0   left  year  life
15          16  right  1902    90
16          17  right  1902    90
17          18  right  1902    90

Tambien es posible combinar algunos de los métodos anteriores para tomar una porción especifica de datos:

In [ ]:
df[['year','cause', 'dead']].head()

   year  cause  dead
0  1890  alive     0
1  1892  alive     0
2  1893  alive     0
3  1894  alive     0
4  1896  alive     0

In [ ]:
df["year"]>=1920

0       False
1       False
2       False
3       False
4       False
        ...
5955    False
5956    False
5957    False
5958    False
5959    False
Name: year, Length: 5960, dtype: bool

\**EJERCICIO 2:** Importe una base de datos en formato .csv o desde excel y haga una familiarización con sus datos

**INSERTAR FILAS O COLUMNAS A UN DATAFRAME**

Hay una gran variedad de formas de añadir filas y columnas en el dataframe, es posible hacer uso del .loc[  ] o tambien es posible utilizar .insert(). Es posible incluso hacer la concatenación de 2 dataframe usando pd.merge(), concat(), or join().

Para nuestro ejemplo puntual, utilizaremos .iloc[ ] y .insert( ) para agregar nuevos datos.

In [10]:
print('Antes: \n', df.tail())
df.loc[5961]=[6173, 'right', 1994, 28, 0, 0, 0, None, 'alive']
print('Despues: \n', df.tail())

Antes:
       Unnamed: 0   left  year  life  dead  acd  kia  inbed  cause
5955        6168  right  1890    46     1    0    0      1  inbed
5956        6169  right  1919    63     1    0    0      1  inbed
5957        6170   left  1876    88     1    0    0      1  inbed
5958        6171   left  1850    65     1    0    0      1  inbed
5959        6172   left  1885    32     1    1    1      0    acd
Despues:
       Unnamed: 0   left  year  life  dead  acd  kia inbed  cause
5956        6169  right  1919    63     1    0    0     1  inbed
5957        6170   left  1876    88     1    0    0     1  inbed
5958        6171   left  1850    65     1    0    0     1  inbed
5959        6172   left  1885    32     1    1    1     0    acd
5961        6173  right  1994    28     0    0    0  None  alive

Note que una nueva muestra o fila ha sido agregada al final del Dataframe. Adicionalmente, tenga en cuenta que en la adición del nuevo dato se definieron los valores de todas las columnas, no hacer esto generará un error, es preferible añadir la palabra None como indicador de la inexistencia del dato

In [11]:
print('Antes: \n', df.tail())
df.loc[5961]=[6174, 'right', 1965, 58, None, None, None, None, 'alive']
print('Despues: \n', df.tail())

Antes:
       Unnamed: 0   left  year  life  dead  acd  kia inbed  cause
5956        6169  right  1919    63     1    0    0     1  inbed
5957        6170   left  1876    88     1    0    0     1  inbed
5958        6171   left  1850    65     1    0    0     1  inbed
5959        6172   left  1885    32     1    1    1     0    acd
5961        6173  right  1994    28     0    0    0  None  alive
Despues:
       Unnamed: 0   left  year  life  dead  acd  kia inbed  cause
5956        6169  right  1919    63   1.0  0.0  0.0     1  inbed
5957        6170   left  1876    88   1.0  0.0  0.0     1  inbed
5958        6171   left  1850    65   1.0  0.0  0.0     1  inbed
5959        6172   left  1885    32   1.0  1.0  1.0     0    acd
5961        6174  right  1965    58   NaN  NaN  NaN  None  alive

In [12]:
df.info()#Note que agregar valores None cambia la info de Non-Null Count

<class 'pandas.DataFrame'>
Index: 5961 entries, 0 to 5961
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5961 non-null   int64
 1   left        5961 non-null   str
 2   year        5961 non-null   int64
 3   life        5961 non-null   int64
 4   dead        5960 non-null   float64
 5   acd         5960 non-null   float64
 6   kia         5960 non-null   float64
 7   inbed       5960 non-null   object
 8   cause       5961 non-null   str
dtypes: float64(3), int64(3), object(1), str(2)
memory usage: 594.7+ KB

Tambien es posible insertar información que no necesariamente se ubique al final de las filas o columnas, en tal caso, puede usar .insert() el cual es aplicable en columnas

In [13]:
print('Antes: \n', df.tail())
df.insert(3,'new2_col', df["year"])#se definen 3 párametros, posición de inserción, nombre de la nueva columna, y valores(int, array o series de pandas)
print('Despues: \n', df.tail())

Antes:
       Unnamed: 0   left  year  life  dead  acd  kia inbed  cause
5956        6169  right  1919    63   1.0  0.0  0.0     1  inbed
5957        6170   left  1876    88   1.0  0.0  0.0     1  inbed
5958        6171   left  1850    65   1.0  0.0  0.0     1  inbed
5959        6172   left  1885    32   1.0  1.0  1.0     0    acd
5961        6174  right  1965    58   NaN  NaN  NaN  None  alive
Despues:
       Unnamed: 0   left  year  new2_col  life  dead  acd  kia inbed  cause
5956        6169  right  1919      1919    63   1.0  0.0  0.0     1  inbed
5957        6170   left  1876      1876    88   1.0  0.0  0.0     1  inbed
5958        6171   left  1850      1850    65   1.0  0.0  0.0     1  inbed
5959        6172   left  1885      1885    32   1.0  1.0  1.0     0    acd
5961        6174  right  1965      1965    58   NaN  NaN  NaN  None  alive

Tenga en cuenta que es posible agregar varios valores definiendo un nuevo DataFrame y utilizanto concat()

**EJERCICIO 3:** Cree un DataFrame por el método que desee y concatenelo a nivel de filas a su Dataframe original. Use la documentación de pandas para investigar como usar el método.

**ELIMINAR FILAS O COLUMNAS DE UN DATAFRAME**

Para la eliminación de filas o columnas se hace uso de .Drop() debe especificar la posición sea por categora en caso de las columnas o por indice en el caso de las filas. Recuerde seleccionar el Axis. Si realizo el ejercicio 3 ya debe de tener claro que  se define 0 para filas y  1 para columnas

In [15]:
df=df.drop(labels='new2_col',axis=1)#para eliminar la columna que añadimos
print(df)

      Unnamed: 0   left  year  life  dead  acd  kia inbed  cause
0              1  right  1890   102   0.0  0.0  0.0     0  alive
1              2   left  1892   100   0.0  0.0  0.0     0  alive
2              3  right  1893    99   0.0  0.0  0.0     0  alive
3              4  right  1894    98   0.0  0.0  0.0     0  alive
4              5  right  1896    96   0.0  0.0  0.0     0  alive
...          ...    ...   ...   ...   ...  ...  ...   ...    ...
5956        6169  right  1919    63   1.0  0.0  0.0     1  inbed
5957        6170   left  1876    88   1.0  0.0  0.0     1  inbed
5958        6171   left  1850    65   1.0  0.0  0.0     1  inbed
5959        6172   left  1885    32   1.0  1.0  1.0     0    acd
5961        6174  right  1965    58   NaN  NaN  NaN  None  alive

[5961 rows x 9 columns]

In [ ]:
df=df.drop(index=[5959, 5958],axis=0) #para eliminar las 2 filas añadidas
print(df)

      Unnamed: 0   left  year  life dead acd kia inbed  cause
0              1  right  1890   102    0   0   0     0  alive
1              2   left  1892   100    0   0   0     0  alive
2              3  right  1893    99    0   0   0     0  alive
3              4  right  1894    98    0   0   0     0  alive
4              5  right  1896    96    0   0   0     0  alive
...          ...    ...   ...   ...  ...  ..  ..   ...    ...
5953        6166  right  1876    37    1   0   0     1  inbed
5954        6167  right  1867    80    1   0   0     1  inbed
5955        6168  right  1890    46    1   0   0     1  inbed
5956        6169  right  1919    63    1   0   0     1  inbed
5957        6170   left  1876    88    1   0   0     1  inbed

[5958 rows x 9 columns]

Tenga en cuenta que los 2 casos expuestos anteriormnente se hizo una asignación del retorno para actualizar df

**RENOMBRAR INDICES DE FILAS O LAS CATEGORIAS DE COLUMNAS**

En ciertos casos puede llegar a ser necesario hacer un cambi de nombres para la referenciación de filas o columnas. En dado caso puede hacer uso del método .rename( )

In [ ]:
print('Antes: \n', df.head())
df=df.rename(index={0:'first'}) #index cambia el valor indicado en la fila
df=df.rename(columns={'year':'years', })#columns cambia el nombre indicado de la columna
print('Despues: \n', df.head())

Antes:
    Unnamed: 0   left  year  life dead acd kia inbed  cause
0           1  right  1890   102    0   0   0   0.0  alive
1           2   left  1892   100    0   0   0   0.0  alive
2           3  right  1893    99    0   0   0   0.0  alive
3           4  right  1894    98    0   0   0   0.0  alive
4           5  right  1896    96    0   0   0   0.0  alive
Despues:
        Unnamed: 0   left  years  life dead acd kia inbed  cause
first           1  right   1890   102    0   0   0   0.0  alive
1               2   left   1892   100    0   0   0   0.0  alive
2               3  right   1893    99    0   0   0   0.0  alive
3               4  right   1894    98    0   0   0   0.0  alive
4               5  right   1896    96    0   0   0   0.0  alive

Nuevamente la actualización de df depende de la asignación.

**ITERACIONES EN UN DATAFRAMES**

En ciertas ocasiones, puede ser necesario iterar a lo largo de todo el dataframe, las iteraciones a lo largo del dataframe pueden definirse como sigue:

In [ ]:
for index, col in df.iterrows():
  print(index)
  print(col)
  print(type(col))
  break
  #print(col['life'])

0
Unnamed: 0        1
left          right
year           1890
life            102
dead              0
acd               0
kia               0
inbed             0
cause         alive
Name: 0, dtype: object
<class 'pandas.core.series.Series'>

Note que mientras index es un valor entero que hace referencia a la posición de la fila tomada, col es una serie de pandas que incluye todas los valores de columna para esa fila en particular.
Una serie de pandas es una estructura unidimensional con etiquetas de eje (incluidas las series temporales).

**EJERCICIO 4:** haga un ciclo iterativo que le permita cambiar los valores de una columna con valores categoricos o objetos a simplemente números.
Use condicionales y tenga en cuenta todos los posibles valores que pyuede tomar el dato en dicha columna para saber cuantos numeros deberia definir.

**FILTRADO USANDO CONDICIONALES**

In [17]:
import pandas as pd
import numpy as np
# Crear un DataFrame de ejemplo
data = {
'Producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Cámara', 'Auriculares',
'Impresora', 'Disco Duro'],
'Precio': [1200, 25, 75, 300, 150, 50, 200, 80],
'Stock': [10, 50, 30, 20, 15, 40, 5, 45],
'Categoria': ['Electrónica', 'Accesorios', 'Accesorios', 'Electrónica', 'Electrónica',
'Accesorios', 'Electrónica', 'Accesorios'],
'Disponible': [True, True, False, True, True, False, True, True]
}
df = pd.DataFrame(data)
print("DataFrame Original:")
df

DataFrame Original:

      Producto  Precio  Stock    Categoria  Disponible
0       Laptop    1200     10  Electrónica        True
1        Mouse      25     50   Accesorios        True
2      Teclado      75     30   Accesorios       False
3      Monitor     300     20  Electrónica        True
4       Cámara     150     15  Electrónica        True
5  Auriculares      50     40   Accesorios       False
6    Impresora     200      5  Electrónica        True
7   Disco Duro      80     45   Accesorios        True

In [19]:
df[df['Precio'] > 100]

    Producto  Precio  Stock    Categoria  Disponible
0     Laptop    1200     10  Electrónica        True
3    Monitor     300     20  Electrónica        True
4     Cámara     150     15  Electrónica        True
6  Impresora     200      5  Electrónica        True

df['Precio'] > 100

**EJERCICIO 5:** REALICE UN FILTRO QUE LE ENTREGUE LOS PRODUCTOS DE ELECTRONICA CON UN STOCK > 10

In [22]:
df

      Unnamed: 0   left  year  life  dead  acd  kia  inbed  cause
0              1  right  1890   102     0    0    0      0  alive
1              2   left  1892   100     0    0    0      0  alive
2              3  right  1893    99     0    0    0      0  alive
3              4  right  1894    98     0    0    0      0  alive
4              5  right  1896    96     0    0    0      0  alive
...          ...    ...   ...   ...   ...  ...  ...    ...    ...
5955        6168  right  1890    46     1    0    0      1  inbed
5956        6169  right  1919    63     1    0    0      1  inbed
5957        6170   left  1876    88     1    0    0      1  inbed
5958        6171   left  1850    65     1    0    0      1  inbed
5959        6172   left  1885    32     1    1    1      0    acd

[5960 rows x 9 columns]

In [24]:
zmyres20=df[(df["left"]=="left") & (df["life"]>20)]
zmyres20.shape

(1101, 9)